### PR TITLE
Added compatibility to Spring Boot v2.5.0

### PR DESCRIPTION
**Pull request by lhmoraes**
Hi @rwanderc please take a look on this PR to support the new Spring Boot version 2.5

PS: The tests should be fixed to support the new changes

### CODE REVIEW

**Comment by ocristian** [comment]
Hi @lhmoraes.
The build has failed. Could you please take a look?
Thanks.

**Comment by fern-we** [comment]
@lhmoraes It looks like it's just checkstyle issues. Can you update the PR?

**Comment by mhewedy** [comment]
For me, I had to follow official support and built on top of it.
see: https://gist.github.com/mhewedy/e4fb38ad944e6d4754a5f38a3b9f4771

**Comment by rwanderc** [comment]
Closing PR in favor of https://github.com/freenowtech/spring-multirabbit/pull/74

**Pull request closed without merging**
